version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ea-im-incident-form-web:
    build:
      target: development
    image: ea-im-incident-form-web-development
    container_name: ea-im-incident-form-web-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
