version: '3.8'

services:
  ea-wq-incident-web:
    build:
      context: .
      target: production
    image: ea-wq-incident-web
    container_name: ea-wq-incident-web
    environment:
      COOKIE_PASSWORD: ${COOKIE_PASSWORD:-cookiecookiecookiecookiecookiecookie}
      # STATIC_CACHE_TIMEOUT_IN_MILLIS: ${STATIC_CACHE_TIMEOUT_IN_MILLIS}
      # COOKIE_TTL_IN_MILLIS: ${COOKIE_TTL_IN_MILLIS}
      EMAIL_TO_ADDRESS: ${EMAIL_TO_ADDRESS}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      NOTIFY_TEMPLATE_ID: ${NOTIFY_TEMPLATE_ID}
