environment: development
name: ea-wq-incident-web
namespace: ea-im
workstream: ea-im
image: ea-wq-incident-web

labels: {}

containerConfigMap:
  name: ea-wq-incident-web-config-map

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ea-incident-form
  cookiePassword: cookiepassword_cookiepassword_cookiepassword_cookiepassword
  sessionTimeoutInMinutes: 20
  staticCacheTimeoutInMillis: 2000000
  cookieTtlInMillis: 2000000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
