{{- include "ffc-helm-library.container-secret" (list . "ea-wq-incident-web.container-secret") -}}
{{- define "ea-wq-incident-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  NOTIFY_API_KEY: {{ .Values.container.notifyApiKey | quote }}
{{- end -}}
