environment: development
name: ea-wq-incident-web
namespace: ea-wq
image: ea-wq-incident-web
workstream: ea-wq

labels:
  component: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ea-wq-incident-web-config-map

containerSecret:
  name: ea-wq-incident-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

container:
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ea-wq
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 80Mi
  limitCpu: 80m
  staticCacheTimeoutInMillis: 54000
  sessionTimeoutInMinutes: 60
  port: 3000
  cookiePassword: passwordpasswordpasswordpasswordpassword
  googleTagManagerKey: GTM-N5QK7RX
  protectiveMonitoringUrl:
  emailToAddress: test@test.com
  notifyApiKey:
  notifyTemplateId:

ingress:
  class: nginx
  endpoint: ea-wq
  server: example.com

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:
  useLinkerd: true

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true
