environment: development
name: ea-wq-incident-web
namespace: ea-wq
image: ea-wq-incident-web
workstream: ea-wq

labels:
  component: web

service:
  port: 80
  type: ClusterIP

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 40m
  limitMemory: 100Mi
  limitCpu: 100m
  sessionTimeoutInMinutes: 60
  port: 3000 
  protectiveMonitoringUrl:

ingress:
  class: nginx
  endpoint: ea-wq
  server: example.com

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReplicas: 2
  maxReplicas: 6
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 5
  imagePullSecret:
  useLinkerd: true

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3