{{- include "ffc-helm-library.container-config-map" (list . "ea-im-incident-form-web.config-map") -}}
{{- define "ea-im-incident-form-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
{{- end -}}
